services:
  # Frontend Application
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-todo-app
    ports:
      - "3000:3000"
    networks:
      - todo-network
    restart: unless-stopped

  # FastAPI Application
  fastapi-app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-todo-app
    ports:
      - "8000:8000"
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017/todo
      - SECRET_KEY=your-super-secret-jwt-key-change-this-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - mongodb
    networks:
      - todo-network
    restart: unless-stopped

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: mongodb-todo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=todo
    volumes:
      - mongodb_data:/data/db
      - ./backend/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - todo-network
    restart: unless-stopped

  # MongoDB Express (Web UI for MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-todo
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - todo-network
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  todo-network:
    driver: bridge